# -*- coding: utf-8 -*-  # Generated by Django 1.10.2 on 2016-12-19 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseWebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_number', models.IntegerField(default=0)),
                ('solve_number', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('block_status', models.CharField(max_length=10)),
                ('contribute_number', models.IntegerField(default=0)),
                ('solve_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='user_list',
            field=models.ManyToManyField(to='elearning_system.User'),
        ),
        migrations.AddField(
            model_name='exercisewebserver',
            name='approver_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_approver', to='elearning_system.User'),
        ),
        migrations.AddField(
            model_name='exercisewebserver',
            name='contributer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contributer',
                                    to='elearning_system.User'),
        ),
        migrations.AddField(
            model_name='exercisewebserver',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning_system.Tag'),
        ),
        migrations.AddField(
            model_name='exercisewebserver',
            name='user_list',
            field=models.ManyToManyField(to='elearning_system.User'),
        ),
        migrations.AddField(
            model_name='errormessage',
            name='reported_exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='elearning_system.ExerciseWebServer'),
        ),
        migrations.AddField(
            model_name='errormessage',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.User'),
        ),
    ]
