# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('block_status', models.CharField(max_length=10)),
            ],
        ),
    ]
