# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisewebserver',
            name='exercise_description',
        ),
        migrations.RemoveField(
            model_name='exercisewebserver',
            name='exercise_name',
        ),
    ]
