# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseWebServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=30)),
                ('view_number', models.IntegerField()),
                ('solve_number', models.IntegerField()),
                ('contributer_id', models.IntegerField()),
                ('approver_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.Role')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSolveExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.ExerciseWebServer')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.User')),
            ],
        ),
        migrations.AddField(
            model_name='exercisewebserver',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.Tag'),
        ),
        migrations.AddField(
            model_name='errormessage',
            name='reported_exercise_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.ExerciseWebServer'),
        ),
        migrations.AddField(
            model_name='errormessage',
            name='reporter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning_system.User'),
        ),
    ]
