# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_system', '0002_auto_20161218_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisewebserver',
            name='tag_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elearning_system.Tag'),
        ),
    ]
