# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_system', '0004_auto_20161220_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisewebserver',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ex_approver', to='elearning_system.User'),
        ),
        migrations.AlterField(
            model_name='exercisewebserver',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_contributor', to='elearning_system.User'),
        ),
        migrations.AlterField(
            model_name='exercisewebserver',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elearning_system.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
    ]
