# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-21 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_system', '0005_auto_20161221_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisewebserver',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_approve', to='elearning_system.User'),
        ),
        migrations.AlterField(
            model_name='exercisewebserver',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_contribute', to='elearning_system.User'),
        ),
    ]
