# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning_system', '0006_auto_20161221_0625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errormessage',
            old_name='exercise_report',
            new_name='exercise_reported',
        ),
        migrations.RenameField(
            model_name='exercisewebserver',
            old_name='user_list',
            new_name='user_solved_list',
        ),
        migrations.AlterField(
            model_name='exercisewebserver',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercise_approved_list', to='elearning_system.User'),
        ),
        migrations.AlterField(
            model_name='exercisewebserver',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_contributed_list', to='elearning_system.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='block_status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
